### ISSUE TITLE
peer to peer code review week3

### ISSUE THREAD

**Issue by supreeti** [sumon766/portfolio-bootstrap#2]
Sumon , You did a great job. I suggest you  to stick to figma design for work section as see project should be aligned  center.
![Screen Shot 2023-02-03 at 12 54 52 PM](https://user-images.githubusercontent.com/6183781/216537851-dc652346-b722-43f2-a5d1-1a6e66ec881a.png)

**Comment by bronnie313** [comment]
Thanks Islam for doing such a great job sofar but there are some little issues that need to be attended to. I suggest you follow the design in the figma for the contact section because the textarea has a different background color and the button too
![Capture](https://user-images.githubusercontent.com/37089236/216539287-29a3e6d6-055f-47e1-bbf5-0c070f0af0c4.JPG)
